// <auto-generated />
namespace Nop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddColumnRating_Order_OrderItemId_ProductReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnRating_Order_OrderItemId_ProductReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201505111853484_AddColumnRating_Order_OrderItemId_ProductReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
