// <auto-generated />
namespace Nop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Order_RemoveRequired_BillingAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_RemoveRequired_BillingAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201505202123015_Order_RemoveRequired_BillingAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
