// <auto-generated />
namespace Nop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AlterColumn_Value_Table_Setting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumn_Value_Table_Setting));
        
        string IMigrationMetadata.Id
        {
            get { return "201508250215236_AlterColumn_Value_Table_Setting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
